<template><div><h2 id="_175-组合两个表" tabindex="-1"><a class="header-anchor" href="#_175-组合两个表"><span><a href="https://leetcode.cn/problems/combine-two-tables/" target="_blank" rel="noopener noreferrer">175. 组合两个表</a></span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">-- 组合两个表</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 左连接以左表为基础，将右表中满足连接条件的记录与左表进行匹配，并保留左表中所有的记录，无论右表中是否有匹配</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 如果右表中没有与左表匹配的记录，则在结果中对应的右表列显示为 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">NULL</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">select</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> FirstName, LastName, City, </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">State</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Person </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">left join</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> Address</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">on</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> Person</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">PersonId</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> Address</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">PersonId</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_176-第二高的薪水" tabindex="-1"><a class="header-anchor" href="#_176-第二高的薪水"><span><a href="https://leetcode.cn/problems/second-highest-salary/" target="_blank" rel="noopener noreferrer">176. 第二高的薪水</a></span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">-- 第二高的薪水</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">select</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> max</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">(salary) </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">as</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> SecondHighestSalary # 将排去所有最大值剩下的数种选择新的最大值</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Employee</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">where</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> salary </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">select</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> max</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">(salary) </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Employee) # 先查询出表中最大的那个值, 筛选出比该值小的所有数</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_1068-产品销售分析-i" tabindex="-1"><a class="header-anchor" href="#_1068-产品销售分析-i"><span><a href="https://leetcode.cn/problems/product-sales-analysis-i/" target="_blank" rel="noopener noreferrer">1068. 产品销售分析 I</a></span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">-- 产品销售分析 I</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">select</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> product_name, </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">year</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">, price </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Sales </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">join</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Product </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">using</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">(product_id);</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 或者使用 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">select</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> product_name, </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">year</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">, price </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Sales, Product </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">where</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> Sales</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">product_id</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">Product</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">product_id</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">; 也是一样的</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


