<template><div><h2 id="_1-1-软件安装需求" tabindex="-1"><a class="header-anchor" href="#_1-1-软件安装需求"><span>1.1 软件安装需求</span></a></h2>
<p>需要先根据基础介绍中的编译软件部分选择需要软件进行安装，后续的演示都以 <code v-pre>VS</code> 作为编译软件。<Plot>说一句写C#的Virtual Studio是世界第一不过分叭</Plot></p>
<h2 id="_1-2-软件安装流程" tabindex="-1"><a class="header-anchor" href="#_1-2-软件安装流程"><span>1.2 软件安装流程</span></a></h2>
<p>首先还是需要先去<a href="https://visualstudio.microsoft.com/zh-hans/" target="_blank" rel="noopener noreferrer">微软官方下载页</a>下载安装包，一般来说Community版本已经足够覆盖大部分使用场景。</p>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-downloadpage.png" alt="install-downloadpage" tabindex="0" loading="lazy"><figcaption>install-downloadpage</figcaption></figure>
<p>点击下载后就会自动开始下载，如果下载比较缓慢或卡顿，需要自行使用 <em>科学上网</em> 的方式进行加速。</p>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-downloadprgress.png" alt="install-downloadprgress" tabindex="0" loading="lazy"><figcaption>install-downloadprgress</figcaption></figure>
<p>下载完成后打开会显示安装引导，需要按照具体的需求进行安装，不同的选择会下载不同框架以及依赖（如果磁盘空间够大的可以当笔者没说 <s>磁盘空间大了不起啊，对不起磁盘空间大真的了不起</s>）。</p>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-exe-open.png" alt="install-exe-open" tabindex="0" loading="lazy"><figcaption>install-exe-open</figcaption></figure>
<p>如果需要添加额外的依赖如不被支持的Net框架，可以通过选择单个组件进行单独添加。</p>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-exe-add.png" alt="install-exe-add" tabindex="0" loading="lazy"><figcaption>install-exe-add</figcaption></figure>
<p>在选择对应的依赖后就可以静待下载完成，有时会遇到进度卡住不动的情况，此时需要使用 <em>科学上网</em> 进行下载。</p>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-exe-download.png" alt="install-exe-download" tabindex="0" loading="lazy"><figcaption>install-exe-download</figcaption></figure>
<p>至此 <code v-pre>VS</code> 的安装已经完成，可以打开 <code v-pre>VS</code> 设置一下喜欢的界面样式了。</p>
<h1 id="项目创建" tabindex="-1"><a class="header-anchor" href="#项目创建"><span>项目创建</span></a></h1>
<p>项目创建在<mark>基础介绍</mark>中讲过非常简便，以下将通过创建三个不同的项目进行演示。</p>
<h2 id="_2-1-console控制台" tabindex="-1"><a class="header-anchor" href="#_2-1-console控制台"><span>2.1 Console控制台</span></a></h2>
<p><strong>cmd命令行</strong>想必大家都比较熟悉，<code v-pre>Console控制台</code> 项目其实本质就是cmd控制台，项目运行后会弹出命令行窗口，根据编写的程序代码进行执行。</p>
<div class="vp-steps"><ol>
<li>首先先打开 <code v-pre>VS</code> 创建新项目，搜索栏搜索 <strong>控制台</strong> ，注意区分后面括号，代表不同的框架，无括号为 <code v-pre>.net</code> ，有括号的为 <code v-pre>.net framework</code> 。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-new.png" alt="install-project-new" tabindex="0" loading="lazy"><figcaption>install-project-new</figcaption></figure>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-console-create-1.png" alt="install-projec-console-create-1" tabindex="0" loading="lazy"><figcaption>install-projec-console-create-1</figcaption></figure>
<ol start="2">
<li>确认选择要创建的项目后，点击下一步，可以修改项目名以及存放位置，不改默认安装目录。<s>安装目录在C盘，C盘那变红都是代码太多害的（暴论）</s> 此处框选出来的设置为 <code v-pre>.sln</code> <strong>解决方案文件</strong>的存放，分开存放有助于后续扩展多项目，按个人需求选择即可。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-console-create-2.png" alt="install-project-console-create-2" tabindex="0" loading="lazy"><figcaption>install-project-console-create-2</figcaption></figure>
<ol start="3">
<li>确认设置完成后，点击下一步会来到具体的框架选择，选择具体的需要的框架即可，其他设置如<strong>容器支持</strong>等，有需要可以点击旁边感叹号进行查看，此处选择<mark>不使用顶级语句</mark>便于展示，其余不过多赘述。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-console-create-3.png" alt="install-project-console-create-3" tabindex="0" loading="lazy"><figcaption>install-project-console-create-3</figcaption></figure>
<ol start="4">
<li>确认设置完成后，点击创建等待后即可完成项目创建。<Plot>是不是很简单？简单就对啦！全都来写C#！</Plot></li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-console-create-4.png" alt="install-project-console-create-3" tabindex="0" loading="lazy"><figcaption>install-project-console-create-3</figcaption></figure>
</div><h3 id="_2-1-1-代码总结" tabindex="-1"><a class="header-anchor" href="#_2-1-1-代码总结"><span>2.1.1 代码总结</span></a></h3>
<div class="language-c# line-numbers-mode" data-highlighter="shiki" data-ext="c#" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-c#"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">// 命名空间：一般为项目名称</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">namespace</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> TestApp</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">    // 类名：与cs文件名相同</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">    internal</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> class</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Program</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    {</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">        //main方法：程序主运行方法</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        static</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> void</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Main</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">string</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        {</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            Console</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">WriteLine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Hello, World!</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>非常简单的命令行代码， <code v-pre>main()</code> 实现了在命令行中打印 <code v-pre>Hello, World!</code>。</p>
<h2 id="_2-2-dll类库" tabindex="-1"><a class="header-anchor" href="#_2-2-dll类库"><span>2.2 Dll类库</span></a></h2>
<p><code v-pre>Dll类库</code> 如果打游戏之类的有时候会遇到dll报错等问题， <code v-pre>Dll类库</code> 是将代码逻辑进行封装后生成的<strong>dll文件</strong>，举个例子如果你只想让别人使用代码，不想让别人看见代码的运行逻辑，那就可以把代码写成<mark>private</mark>的，只留外部调用的方法为<mark>public</mark>的，这样在生成dll后反编译也只会显示方法名。</p>
<p>如果感觉比较难以理解的话，可以先初步把<strong>dll文件</strong>理解为存放代码的单独仓库，这个仓库里的所有代码可以给不同项目使用。</p>
<div class="vp-steps"><ol>
<li>首先先打开 <code v-pre>VS</code> 创建新项目，搜索栏搜索 <strong>类库</strong> ，注意区分后面括号，代表不同的框架，无括号为 <code v-pre>.net</code> ，有括号的为 <code v-pre>.net framework</code> 。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-new.png" alt="install-project-new" tabindex="0" loading="lazy"><figcaption>install-project-new</figcaption></figure>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-dll-create-1.png" alt="install-projec-dll-create-1" tabindex="0" loading="lazy"><figcaption>install-projec-dll-create-1</figcaption></figure>
<ol start="2">
<li>确认选择要创建的项目后，点击下一步，可以修改项目名以及存放位置，不改默认安装目录。（一般类库会作为项目被其他项目引用，记得放好位置避免移动后其他项目直接依赖丢失 <Plot>别问为什么笔者会知道</Plot>）此处框选出来的设置为 <code v-pre>.sln</code> <strong>解决方案文件</strong>的存放，分开存放有助于后续扩展多项目，按个人需求选择即可。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-dll-create-2.png" alt="install-project-dll-create-2" tabindex="0" loading="lazy"><figcaption>install-project-dll-create-2</figcaption></figure>
<ol start="3">
<li>确认设置完成后，点击下一步会来到具体的框架选择，选择具体的需要的框架即可。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-dll-create-3.png" alt="install-project-dll-create-3" tabindex="0" loading="lazy"><figcaption>install-project-dll-create-3</figcaption></figure>
<ol start="4">
<li>确认设置完成后，点击创建等待后即可完成项目创建。<Plot>是都说很简单啦~</Plot></li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-dll-create-4.png" alt="install-project-dll-create-3" tabindex="0" loading="lazy"><figcaption>install-project-dll-create-3</figcaption></figure>
</div><h3 id="_2-2-1-代码总结" tabindex="-1"><a class="header-anchor" href="#_2-2-1-代码总结"><span>2.2.1 代码总结</span></a></h3>
<div class="language-c# line-numbers-mode" data-highlighter="shiki" data-ext="c#" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-c#"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">// 命名空间：一般为项目名称</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">namespace</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> TestClassLibrary</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">    // 类名：与cs文件名相同</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">    public</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> class</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Class1</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    {</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>一个空的dll文件， <code v-pre>Class1</code> 中可以编写需求的逻辑方法，最后生成<strong>dll文件</strong>使用，也可以通过直接引用项目调用内部文件。</p>
<h2 id="_2-3-asp-net-core-web-api" tabindex="-1"><a class="header-anchor" href="#_2-3-asp-net-core-web-api"><span>2.3 ASP.NET Core Web API</span></a></h2>
<p><code v-pre>ASP.NET Core Web API</code> 是最常用的Web API项目，作用就是搭建可用于部署的Web API，笔者自用部署于<a href="https://blog.csdn.net/qq_46175823/article/details/111168591" target="_blank" rel="noopener noreferrer">IIS服务器</a>，通俗一点来说就是在服务器上部署一个可以调用的接口，举个例子网页的登录操作其实就是调用了登录接口。</p>
<div class="vp-steps"><ol>
<li>首先先打开 <code v-pre>VS</code> 创建新项目，搜索栏搜索 <strong>ASP.NET</strong> ，选择 <code v-pre>ASP.NET Core Web API</code> 项目。至于上面那个Web应用，笔者只能说很不好用，不如去学习一下 <code v-pre>React</code> 等其他前端语言做到前后端分离 <s>（谁问你了）</s>。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-new.png" alt="install-project-new" tabindex="0" loading="lazy"><figcaption>install-project-new</figcaption></figure>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-api-create-1.png" alt="install-projec-api-create-1" tabindex="0" loading="lazy"><figcaption>install-projec-api-create-1</figcaption></figure>
<ol start="2">
<li>确认选择要创建的项目后，点击下一步，可以修改项目名以及存放位置，不改默认安装目录。此处框选出来的设置为 <code v-pre>.sln</code> <strong>解决方案文件</strong>的存放，分开存放有助于后续扩展多项目，按个人需求选择即可。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-api-create-2.png" alt="install-project-api-create-2" tabindex="0" loading="lazy"><figcaption>install-project-api-create-2</figcaption></figure>
<ol start="3">
<li>确认设置完成后，点击下一步会来到具体的框架选择，选择具体的需要的框架即可。其他设置如<strong>容器支持</strong>等，有需要可以点击旁边感叹号进行查看，此处不过多赘述。</li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-api-create-3.png" alt="install-project-api-create-3" tabindex="0" loading="lazy"><figcaption>install-project-api-create-3</figcaption></figure>
<ol start="4">
<li>确认设置完成后，点击创建等待后即可完成项目创建。<Plot>简单吗？简单...吧</Plot></li>
</ol>
<figure><img src="@source/1.编程语言/3.CSharp/assets/install-project-api-create-4.png" alt="install-project-api-create-4" tabindex="0" loading="lazy"><figcaption>install-project-api-create-4</figcaption></figure>
</div><h3 id="_2-3-1-代码总结" tabindex="-1"><a class="header-anchor" href="#_2-3-1-代码总结"><span>2.3.1 代码总结</span></a></h3>
<div class="language-c# line-numbers-mode" data-highlighter="shiki" data-ext="c#" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-c#"><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">namespace</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> TestWebApplication</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">    public</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> class</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Program</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    {</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        public</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> static</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> void</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Main</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">string</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        {</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">            var</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> builder</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> WebApplication</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">CreateBuilder</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">            // Add services to the container.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            builder</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Services</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">AddControllers</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            builder</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Services</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">AddEndpointsApiExplorer</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">            // 自带的Swagger调试路由</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            builder</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Services</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">AddSwaggerGen</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">            var</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> app</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> builder</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Build</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">            // Configure the HTTP request pipeline.</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">            if</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Environment</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">IsDevelopment</span><span style="--shiki-light:#999999;--shiki-dark:#666666">())</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">            {</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">UseSwagger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">UseSwaggerUI</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">            }</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">UseHttpsRedirection</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">UseAuthorization</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">MapControllers</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Run</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>Web API</code> 的总启动项，在app中可以进行中间件注册，也可以在此处配置Cors解决跨域问题。</p>
<div class="language-c# line-numbers-mode" data-highlighter="shiki" data-ext="c#" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-c#"><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">namespace</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> TestWebApplication</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">    public</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> class</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> WeatherForecast</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    {</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        public</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> DateOnly</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Date</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> get</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> set</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        public</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> int</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> TemperatureC</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> get</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> set</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        public</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> int</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> TemperatureF</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =></span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 32</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> +</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">int</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">TemperatureC</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> /</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0.5556</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">        // string? 表示可以为string或null类型</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        public</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> string</span><span style="--shiki-light:#999999;--shiki-dark:#666666">?</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Summary</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> get</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> set</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>初始生成的实体类，若选择了空白项目则不会生成，定义了需要的实体类属性，用于给其他代码调用。</p>
<div class="language-c# line-numbers-mode" data-highlighter="shiki" data-ext="c#" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-c#"><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">using</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Microsoft</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">AspNetCore</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">Mvc</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">namespace</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> TestWebApplication</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">Controllers</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    [</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ApiController</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    [</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">Route</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">[controller]</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)]</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">    public</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> class</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> WeatherForecastController</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> :</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> ControllerBase</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    {</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        private</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> static</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> readonly</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> string</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Summaries</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> new</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[]</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        {</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">            "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Freezing</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Bracing</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Chilly</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Cool</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Mild</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Warm</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Balmy</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Hot</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Sweltering</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Scorching</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        };</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        private</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> readonly</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> ILogger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">WeatherForecastController</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> _logger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        public</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> WeatherForecastController</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ILogger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">WeatherForecastController</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> logger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        {</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">            _logger</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> logger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        }</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        [</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">HttpGet</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Name</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">GetWeatherForecast</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)]</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        public</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> IEnumerable</span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">WeatherForecast</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Get</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        {</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">            // 典型的Linq写法</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">            return</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Enumerable</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Range</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 5</span><span style="--shiki-light:#999999;--shiki-dark:#666666">).</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Select</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">index</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =></span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> new</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> WeatherForecast</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">            {</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                Date</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> DateOnly</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">FromDateTime</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">DateTime</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Now</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">AddDays</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">index</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)),</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                TemperatureC</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Random</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Shared</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Next</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">-</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">20</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 55</span><span style="--shiki-light:#999999;--shiki-dark:#666666">),</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                Summary</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Summaries</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Random</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Shared</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Next</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Summaries</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Length</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)]</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">            })</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">            .</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">ToArray</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">        }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>初始生成的接口代码，若选择了空白项目则不会生成，<code v-pre>[Route(&quot;[controller]&quot;)]</code> 和 <code v-pre>[HttpGet(Name = &quot;GetWeatherForecast&quot;)]</code> 表示接口的url路由，组合后的url路由为 <code v-pre>WeatherForecast\GetWeatherForecast</code>。</p>
<p>上述三个文件为 <code v-pre>Web API</code> 项目的基础构成，通过启动项目后可以在swagger页面进行调试，测试接口来获取天气。</p>
<h3 id="_2-3-2-文件结构总结" tabindex="-1"><a class="header-anchor" href="#_2-3-2-文件结构总结"><span>2.3.2 文件结构总结</span></a></h3>
<div class="vp-file-tree"><FileTreeNode expanded type="folder" filename="TestWebApplication" :level="0">
<template #icon><VPIcon provider="iconify" name="vscode-icons:default-folder" /></template><FileTreeNode expanded type="folder" filename="Properties" :level="2">
<template #icon><VPIcon provider="iconify" name="vscode-icons:default-folder" /></template><FileTreeNode type="file" filename="launchSettings.json" :level="4">
<template #icon><VPIcon provider="iconify" name="vscode-icons:file-type-json" /></template>
</FileTreeNode>
</FileTreeNode>
<FileTreeNode expanded type="folder" filename="Controllers" :level="2">
<template #icon><VPIcon provider="iconify" name="vscode-icons:folder-type-controller" /></template><FileTreeNode type="file" filename="WeatherForecastController.cs" :level="4">
<template #icon><VPIcon provider="iconify" name="vscode-icons:file-type-csharp" /></template>
</FileTreeNode>
</FileTreeNode>
<FileTreeNode type="file" filename="appsettings.json" :level="2">
<template #icon><VPIcon provider="iconify" name="vscode-icons:file-type-json" /></template>
</FileTreeNode>
<FileTreeNode type="file" filename="Program.cs" :level="2">
<template #icon><VPIcon provider="iconify" name="vscode-icons:file-type-csharp" /></template>
</FileTreeNode>
<FileTreeNode type="file" filename="WeatherForecast.cs" :level="2">
<template #icon><VPIcon provider="iconify" name="vscode-icons:file-type-csharp" /></template>
</FileTreeNode>
</FileTreeNode></div>
<p><code v-pre>Web API</code> 项目的文件结构如上，总体结构比较简单，<code v-pre>Controllers</code> 用于存放所有的接口文件，如有分离的需求可以进一步创建 <code v-pre>Models</code> ，<code v-pre>Services</code> 文件夹进行存放对应的实体类文件和业务逻辑文件。</p>
<ul>
<li><code v-pre>launchSettings.json</code> 为<strong>项目启动设置</strong>，可以修改启动的端口号等设置。</li>
<li><code v-pre>WeatherForecastController.cs</code> 为<strong>接口文件</strong>，编写具体接口逻辑。</li>
<li><code v-pre>appsettings.json</code> 为<strong>项目配置文件</strong>，可以在其中添加配置后在程序内读取。</li>
<li><code v-pre>Program.cs</code> 为<strong>项目启动文件</strong>，可以在里面添加注册中间件或初始化程序配置。</li>
<li><code v-pre>WeatherForecast.cs</code> 为<strong>实体类文件</strong>，可通过创建 <code v-pre>Models</code> 文件夹统一管理。</li>
</ul>
<h1 id="创建总结" tabindex="-1"><a class="header-anchor" href="#创建总结"><span>创建总结</span></a></h1>
<p>从项目创建上来说，<code v-pre>VS</code> 的创建流程简便，可以轻松创建对应需求的项目文件，本篇仅为举例，如有需求可以自行前往 <a href="https://learn.microsoft.com/zh-cn/visualstudio/ide/solutions-and-projects-in-visual-studio?view=visualstudio" target="_blank" rel="noopener noreferrer">了解解决方案和项目</a> 查看是否存在需要构建的项目和教程。如需打开已有项目，点击已存在的 <code v-pre>.sln</code> 解决方案文件后，<code v-pre>VS</code> 就会进行加载，nuget包等相关依赖也会自动下载配置.但是要注意<mark>如果引用其他本地项目，在上传代码被拉取下来后，会由于本地路径的缺失，导致项目依赖警告</mark>。</p>
</div></template>


