<template><div><h1 id="_1-debug-release" tabindex="-1"><a class="header-anchor" href="#_1-debug-release"><span>1.debug/release</span></a></h1>
<p><code v-pre>gdb</code>是一款<code v-pre>Linux</code>下的一款调试器，在没有图形化界面下，是一种不错的调试方案（虽然在一般的开发环境中很少会使用<code v-pre>gdb</code>）</p>
<p>不过要使用<code v-pre>gdb</code>，就先要了解<code v-pre>debug</code>和<code v-pre>release</code>版本。</p>
<p>发布软件的时候有一种叫<code v-pre>debug</code>版本，另外一种叫<code v-pre>release</code>版本，在<code v-pre>debug</code>中包含了调试信息，所以一般生成的<code v-pre>debug</code>文件会比<code v-pre>release</code>大一些。而<code v-pre>release</code>版本文件对程序做了较大的优化，因此文件会小一些。</p>
<p>而<code v-pre>gcc/g++</code>默认生成的可执行程序是<code v-pre>release</code>版本。但是<code v-pre>gdb</code>只能调试<code v-pre>debug</code>版本的文件，这个时候就需要给<code v-pre>gcc/g++</code>添加<code v-pre>-g</code>选项来生成<code v-pre>release</code>版本的文件。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> cat</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.c</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">#include &#x3C;stdio.h></span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num1,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sum</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num1</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> +</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    return</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sum</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num1</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 10</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num2</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 5</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    int</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sum</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">num1,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    printf</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">"num1: %d\n"</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    printf</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">"num2: %d\n"</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> num2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    printf</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">"sum: %d\n"</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sum</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    return</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gcc</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.c</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a.out-release</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gcc</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.c</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -g</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a.out-debug</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ls</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">a.out</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a.out-g</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.c</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果我们需要查看<code v-pre>release</code>文件中的调试信息，可以使用命令<code v-pre>readelf -S 文件名</code>来读取可执行程序的数据段格式，<code v-pre>-S</code>表示读取各个段，在下面可以查看到<code v-pre>debug</code>信息，而没有带<code v-pre>-g</code>选项生成的可执行程序则没有这一信息（这些试着操作一下，知道行）。</p>
<blockquote>
<p>补充：再编译原理中，<code v-pre>Linux</code>中形成的可执行程序格式不是立刻全部变成二进制的，而是变成<code v-pre>ELF</code>格式，内部含有各种数据段...</p>
</blockquote>
<p>利用管道工具可以让我们更加清晰看到这一现象：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> readelf</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -S</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a.out-release</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> grep</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -i</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> debug</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> readelf</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -S</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a.out-debug</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> grep</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -i</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> debug</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  [</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">27</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> .debug_aranges</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">    PROGBITS</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">         0000000000000000</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">  00001061</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  [</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">28</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> .debug_info</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       PROGBITS</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">         0000000000000000</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">  00001091</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  [</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">29</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> .debug_abbrev</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">     PROGBITS</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">         0000000000000000</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">  00001199</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  [</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">30</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> .debug_line</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       PROGBITS</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">         0000000000000000</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">  00001224</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  [</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">31</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> .debug_str</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">        PROGBITS</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">         0000000000000000</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  0000126c</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="_2-gdb的基本操作" tabindex="-1"><a class="header-anchor" href="#_2-gdb的基本操作"><span>2.gdb的基本操作</span></a></h1>
<h2 id="_2-1-打开退出命令" tabindex="-1"><a class="header-anchor" href="#_2-1-打开退出命令"><span>2.1.打开退出命令</span></a></h2>
<ol>
<li>
<p>打开<code v-pre>gdb</code>调试界面：<code v-pre>gdb debug版的可执行程序</code></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gdb</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a.out-debug</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">GNU</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> gdb</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (GDB) Red Hat Enterprise Linux 7.6.1-120.el7</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Copyright</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (C) 2013 Free Software Foundation, Inc.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">License</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> GPLv3+:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> GNU</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> GPL</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> version</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 3</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> or</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> later</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> &#x3C;</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">http://gnu.org/licenses/gpl.htm</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">l</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">This</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> is</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> free</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> software:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> you</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> are</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> free</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> change</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> and</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> redistribute</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> it.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">There</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> is</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> NO</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> WARRANTY,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> extent</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> permitted</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> by</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> law.</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  Type</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">show copying</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">and</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">show warranty</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> for</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> details.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">This</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> GDB</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> was</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> configured</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> as</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">x86_64-redhat-linux-gnu</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">For</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> bug</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> reporting</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> instructions,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> please</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> see:</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">http://www.gnu.org/software/gdb/bugs/</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">...</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Reading</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> symbols</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> from</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /home/ljp/LimouCodeFile/CodeFile_2/MyFile_2023_9_25/a.out-debug...done.</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">gdb</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>退出<code v-pre>gdb</code>调试界面：使用<code v-pre>[ctrl + d]</code>或者<code v-pre>quit</code>（同时清空断点信息）</p>
</li>
</ol>
<h2 id="_2-2-查看代码命令" tabindex="-1"><a class="header-anchor" href="#_2-2-查看代码命令"><span>2.2.查看代码命令</span></a></h2>
<ol>
<li><code v-pre>l/list [行号]</code>：为查看调试的代码，每次显示<code v-pre>10</code>行（<code v-pre>list 0</code>可以重头开始看源代码文本）</li>
<li><code v-pre>l/list [函数名]</code>：列出某个函数的源代码上下文</li>
</ol>
<h2 id="_2-3-断点操作命令" tabindex="-1"><a class="header-anchor" href="#_2-3-断点操作命令"><span>2.3.断点操作命令</span></a></h2>
<ol>
<li><code v-pre>b/break [源文件名] 源代码行号</code>：设置断点，可以在某个源文件（因为有可能会有多个文件）的特定行号或函数名处设置断点（并且生成的断点编号一直是递增的）</li>
<li><code v-pre>watch</code>设置观察点，当指定变量的值发生改变时中断程序执行（不过要在调试过程中才能设置）</li>
<li><code v-pre>delete 断点/观察点编号</code>：删除断点/观察点，不是使用行号删除，而是删除断点对应的编号，删除所有断点就是<code v-pre>delete breakpoints</code>，注意这里就不需要指定文件，因为这里不是靠指定的行号，而是断点编号来取消断点的</li>
<li><code v-pre>disable 断点/观察点编号</code>：禁用断点/观察点，不是使用行号删除，而是断点对应的编号，禁用所有断点就是<code v-pre>disable breakpoints</code></li>
<li><code v-pre>enable 断点编号/观察点</code>：启用断点/观察点，不是使用行号删除，而是断点对应的编号，开启所有断点就是<code v-pre>enable breakpoints</code></li>
<li><code v-pre>info/i b</code>：查看当前设置的所有断点/观察点。其中，查看断点是否被启用在使用命令<code v-pre>info b</code>里的<code v-pre>Enb</code>那一列，观察点通常被标记为 <code v-pre>hw watchpoint</code>等字样，而断点通常被标记为 <code v-pre>breakpoint</code>（这里还可以查看一个断点被命中的次数）</li>
</ol>
<blockquote>
<p>补充<code v-pre>1</code>：当您退出<code v-pre>gdb</code>的时候，所有的断点/观察点信息会被自动清除。</p>
<p>补充<code v-pre>2</code>：断点的禁用和启用也叫作“使能断点”。</p>
</blockquote>
<h2 id="_2-4-执行相关命令" tabindex="-1"><a class="header-anchor" href="#_2-4-执行相关命令"><span>2.4.执行相关命令</span></a></h2>
<ol>
<li><code v-pre>r/run</code> ：<code v-pre>run</code> 命令用于开始程序的执行。如果您在 <code v-pre>gdb</code> 中设置了断点或观察点，在使用 <code v-pre>run</code> 命令后，程序将会在第一个断点或观察点处暂停执行，此时您可以进行调试操作（例如单步执行、查看变量值等），类似<code v-pre>VS 2022</code>中第一次按下<code v-pre>[F5]</code>快捷键开始调试</li>
<li><code v-pre>c/continue</code>：在使用<code v-pre>r</code>启用调试后，可以使用<code v-pre>c</code>来跳转下一个断点，类似<code v-pre>VS 2022</code>中继续使用<code v-pre>[F5]</code>快捷键</li>
<li><code v-pre>n/next</code>：逐过程执行程序，但不进入函数内部，相当于<code v-pre>VS 2022</code>中的<code v-pre>[F10]</code>快捷键</li>
<li><code v-pre>s/step</code>：逐语句执行程序，进入函数内部，相当于<code v-pre>VS 2022</code>中的<code v-pre>[F11]</code>快捷键</li>
<li><code v-pre>unitl 行号</code>：可以跳转到行号出的代码，在使用<code v-pre>for</code>循环的时候很有用，不建议使用这个命令从<code v-pre>main()</code>跳到其他函数，这是一种局部性的跳转</li>
<li><code v-pre>finish</code>：执行完当前函数并返回到调用者，并且停下来，这是一种全局性的跳转</li>
</ol>
<h2 id="_2-5-程序状态命令" tabindex="-1"><a class="header-anchor" href="#_2-5-程序状态命令"><span>2.5.程序状态命令</span></a></h2>
<ol>
<li><code v-pre>display 变量名</code>：每次停在断点处时，自动显示指定变量的值，并且会显示对应的编号标识</li>
<li><code v-pre>undisplay 变量编号</code>：则取消显示对应编号的变量的值（注意这里使用的是变变量编号）</li>
<li><code v-pre>print(变量)或p 变量</code>：打印变量的值</li>
<li><code v-pre>info locals</code>：查看当前函数/栈帧的所有局部变量</li>
<li><code v-pre>info args</code>：查看当前函数的参数</li>
<li><code v-pre>bt/backtrace</code>：显示当前的函数调用堆栈。<code v-pre>frame</code>切换到指定的堆栈帧。<code v-pre>up</code>切换到上一个堆栈帧，<code v-pre>down</code>切换到下一个堆栈帧</li>
<li><code v-pre>x</code>：以十六进制格式查看内存内容</li>
</ol>
<h2 id="_2-5-其他常用命令" tabindex="-1"><a class="header-anchor" href="#_2-5-其他常用命令"><span>2.5.其他常用命令</span></a></h2>
<ol>
<li>
<p><code v-pre>h/help</code>：获取帮助信息</p>
</li>
<li>
<p><code v-pre>set var 变量名</code>可：以直接篡改修改某变量的值，有的时候需要查验在同一份代码下不同变量数据的表现</p>
</li>
<li>
<p><code v-pre>show</code>：显示当前的设置参数</p>
</li>
</ol>
<blockquote>
<p>补充：由于<code v-pre>gdb</code>有很多重复操作，因此如果需要重复使用一个命令，在<code v-pre>gdb</code>中输入第一次命令后，往后只不断按需要回车即可重复使用该命令。</p>
</blockquote>
<h1 id="_3-gdb的进阶操作" tabindex="-1"><a class="header-anchor" href="#_3-gdb的进阶操作"><span>3.gdb的进阶操作</span></a></h1>
<p>在设计多进程和线程代码中，还有很多相关的<code v-pre>gdb</code>命令，这些也值得看一下。</p>
</div></template>


