<template><div><h2 id="_1-内容概要" tabindex="-1"><a class="header-anchor" href="#_1-内容概要"><span>1.内容概要</span></a></h2>
<p>为了完善业务逻辑，开发人员必须细致地考虑应用程序所有可能遇到的边界情况，并为这些边界情况设计合适的规则。当买家单击将商品添加到购物车时，应用程序会向购物车数据库表中添加一个条目，将该用户 <code v-pre>ID</code> 与商品 <code v-pre>ID</code> 关联起来。 虽然一次编写出完美应用程序的可能性微乎其微，但在大多数情况下，开发人员可以从上述的业务逻辑出发，编写出符合业务逻辑的应用程序，并不断测试直到满足用户的需求。 根据业务逻辑设计自动化系统，驱动正常运行的产品和系统，是一个人类认知上的非凡壮举。</p>
<p>幸运的是，对日益壮大的机器学习科学家群体来说，实现很多任务的自动化并不再屈从于人类所能考虑到的逻辑。想象一下，假如开发人员要试图解决以下问题之一：</p>
<ul>
<li>编写一个应用程序，接受地理信息、卫星图像和一些历史天气信息，并预测明天的天气；</li>
<li>编写一个应用程序，接受自然文本表示的问题，并正确回答该问题；</li>
<li>编写一个应用程序，接受一张图像，识别出该图像所包含的人，并在每个人周围绘制轮廓；</li>
<li>编写一个应用程序，向用户推荐他们可能喜欢，但在自然浏览过程中不太可能遇到的产品。</li>
</ul>
<p>在这些情况下，即使是顶级程序员也无法提出完美的解决方案， 原因可能各不相同。有时任务可能遵循一种随着时间推移而变化的模式，我们需要程序来自动调整。有时任务内的关系可能太复杂（比如像素和抽象类别之间的关系），需要数千或数百万次的计算。 即使人类的眼睛能毫不费力地完成这些难以提出完美解决方案的任务，这其中的计算也超出了人类意识理解范畴。 <strong>机器学习</strong> 是一类强大的可以从经验中学习的技术。通常采用观测数据或与环境交互的形式，机器学习算法会积累更多的经验，其性能也会逐步提高。相反，对于刚刚所说的电子商务平台，如果它一直执行相同的业务逻辑，无论积累多少经验，都不会自动提高，除非开发人员认识到问题并更新软件。</p>
<h2 id="_2-环境配置" tabindex="-1"><a class="header-anchor" href="#_2-环境配置"><span>2.环境配置</span></a></h2>
<ul>
<li>前往 <a href="https://www.anaconda.com/download/success" target="_blank" rel="noopener noreferrer">官方文档</a> 获取对应的 <code v-pre>Conda</code> 安装脚本</li>
<li>根据这个老哥的 <a href="https://zhuanlan.zhihu.com/p/459607806" target="_blank" rel="noopener noreferrer">指引</a>，安装 <code v-pre>Conda</code> 搭建虚拟环境</li>
<li>根据 <a href="https://zh.d2l.ai/chapter_installation/index.html" target="_blank" rel="noopener noreferrer">《动手学深度学习》</a> 安装 <code v-pre>torch、torchvision、d2l</code></li>
</ul>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> pip3</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> torch</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> torchvision</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> torchaudio</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --index-url</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> https://download.pytorch.org/whl/cu121</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> pip3</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> d2l==</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0.17.6</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> conda</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> create</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --name</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> learn</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> python=</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">3.9</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -y</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> # 创建环境</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> conda</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> activate</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> learn</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> # 切换环境</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> conda</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> deactivate</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> # 退出环境</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果嫌弃下载得比较缓慢，可以利用 <code v-pre>tmux</code> 的分离功能慢慢下载。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 分离会话</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> tmux</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> # Ctrl+b 后按 d 这样就可以脱离当前终端时刻运行</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 查看会话</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> tmux</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ls</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 恢复会话</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> tmux</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> attach</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -t</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> &#x3C;</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">会话名称或编</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">号</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后还需要下载书籍代码。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> mkdir</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> d2l-zh</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#x26;&#x26;</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> cd</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> d2l-zh</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> curl</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> https://zh-v2.d2l.ai/d2l-zh-2.0.0.zip</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -o</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> d2l-zh.zip</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> apt</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> update</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#x26;&#x26;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> apt</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> unzip</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#x26;&#x26;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> unzip</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> d2l-zh.zip</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#x26;&#x26;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> rm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> d2l-zh.zip</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> cd</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> pytorch</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> jupyter</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> notebook</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> # 在 Web 浏览器中打开 http://localhost:8888 阅读 Jupyter 笔记本</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_3-目录大纲" tabindex="-1"><a class="header-anchor" href="#_3-目录大纲"><span>3.目录大纲</span></a></h2>
<p>快速入门之前先预览一下学习大纲。</p>
<Mermaid code="eJyNkcFOwkAQhs/0KZreeQWfwJPXhoOpoc2GEKEHt5yaAE1NVDQBxUBUErSNpkVtgtKKvAzbqW/hbpfGYmri3Dr/9890/lWb+4eauLsnYHygyhLxHtaLOzJ1IHyVKqIg0mKKWC7viEipNylyG8LEJFaX+AupkhKsmMipBsbVmizF45Bcu5uBtgUvURGNVR0jRZZg9E66QTx4pga+oYjW0VGNzYb7G4h6sLyAaEwHE/spR7PiIN+A2Qf1hKvYdPLOvz0IcQ85fQNn9j8P1jaez0c4++0p/YSIWIjJavQ1nGch8pzTS6maYi0DtWiGgRt3eixJe57PI6MMTa/K0vpjSE4uwb+Kg0ERhXRcpyv9CUNMJ2kvC6mGjrJXSxwrcY63/tswFHpcMvMS1yTTDpxbTC6xNj+fqb4HUXu7bxg0krAPfZf2hW8PNATD"></Mermaid><h2 id="_4-体验代码" tabindex="-1"><a class="header-anchor" href="#_4-体验代码"><span>4.体验代码</span></a></h2>
<p>待补充...</p>
</div></template>


