<template><div><blockquote>
<p>概要：...</p>
</blockquote>
<blockquote>
<p>资料：<a href="https://www.runoob.com/nodejs/nodejs-tutorial.html" target="_blank" rel="noopener noreferrer">Node.js 菜鸟教程</a> 和 <a href="https://nodejs.org/docs/latest/api/synopsis.html" target="_blank" rel="noopener noreferrer">Node.js 官方文档</a> 就很够用了。</p>
</blockquote>
<hr>
<h2 id="_1-安装-node-js-软件" tabindex="-1"><a class="header-anchor" href="#_1-安装-node-js-软件"><span>1.安装 Node.js 软件</span></a></h2>
<p><code v-pre>Windows</code> 可以到 <a href="https://nodejs.org/en/download" target="_blank" rel="noopener noreferrer">Node.js 官网处下载</a>，<code v-pre>Linux</code> 可以使用包管理器下载，这里举一个 <code v-pre>Ubuntu</code> 的例子，如下操作即可。</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 更新包管理器并且安装相关依赖</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> apt</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> update</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#x26;&#x26;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> apt</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> curl</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 添加 NodeSource 的 PPA, 可选择安装最新的 LTS 版本或当前的版本</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">curl</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -fsSL</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> https://deb.nodesource.com/setup_lts.x</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> sudo</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -E</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> bash</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 如果你想安装最新的稳定版本(Current)，可以使用 curl -fsSL https://deb.nodesource.com/setup_current.x | # sudo -E bash -</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 Node.js</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">sudo</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> apt</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> nodejs</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 检查 Node.js 和 npm 的版本</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">node</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -v</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -v</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2-解析-node-js-内部" tabindex="-1"><a class="header-anchor" href="#_2-解析-node-js-内部"><span>2.解析 Node.js 内部</span></a></h2>
<p>当您下载和安装 <code v-pre>Node.js</code> 后，实际上下载了以下几种工具和组件：</p>
<ol>
<li><strong>运行时环境</strong>：这是核心组件，提供了运行 <code v-pre>JS</code> 代码的环境。包含了 <code v-pre>V8 JS</code> 引擎以及执行 <code v-pre>JS</code> 代码所需的各种底层系统库和 <code v-pre>API</code>。</li>
<li><strong>npm 包管理器</strong>：全称是 <code v-pre>Node Package Manager</code> 这是 <code v-pre>Node.js</code> 的默认包管理器，使得 <code v-pre>Node.js</code> 具备了现代高级编程语言的资格，主要用于管理和安装 <code v-pre>JS</code> 包。具体来说 <code v-pre>npm</code> 是一个命令行工具，帮助你安装、更新、卸载和发布和 <code v-pre>Node.js</code> 相关的软件包。</li>
<li><strong>核心模块</strong>：<code v-pre>Node.js</code> 除了支持基本的 <code v-pre>JS</code> 语法，还包含一组内置的核心模块，例如 <code v-pre>fs(文件系统)</code>、<code v-pre>http(HTTP 服务)</code>、<code v-pre>path(路径处理)</code>等，这些模块不需要额外安装，可以直接在 <code v-pre>Node.js</code> 应用程序中使用。</li>
<li><strong>命令行工具</strong>：包括 <code v-pre>node</code> 本身的一些命令，使用 <code v-pre>node xxx.js</code> 可以在运行时环境下运行 <code v-pre>JS</code> 程序，甚至可以打断点进行调试。</li>
<li>...</li>
</ol>
<blockquote>
<p>补充：不过在早些版本的 <code v-pre>Nodo.js</code> 下载的过程中，可能不会包含太多的工具而只有 <code v-pre>JS</code> 运行环境和 <code v-pre>node</code> 命令行程序（这点我在我的 <code v-pre>Centos7</code> 服务器中就遇到了，没有把 <code v-pre>npm</code> 也下载下来的情况）。</p>
</blockquote>
<h2 id="_3-使用-node-js-工具" tabindex="-1"><a class="header-anchor" href="#_3-使用-node-js-工具"><span>3.使用 Node.js 工具</span></a></h2>
<h3 id="_3-1-使用-node-工具" tabindex="-1"><a class="header-anchor" href="#_3-1-使用-node-工具"><span>3.1.使用 node 工具</span></a></h3>
<h4 id="_3-1-1-运行-js-代码" tabindex="-1"><a class="header-anchor" href="#_3-1-1-运行-js-代码"><span>3.1.1.运行 JS 代码</span></a></h4>
<p>我们来尝试使用最原生的方法来使用 <code v-pre>node</code> 命令行工具运行最基本的 <code v-pre>JS</code> 代码，如下命令行来展示。</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 使用 node 运行原生 JS 代码</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vim</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> cat</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">console.log(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">"Hello World"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> node</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Hello</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> World</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>node</code> 本身还提供了和 <code v-pre>python</code> 类似的 <code v-pre>REPL</code> 交互模式，直接输入 <code v-pre>node</code> 指令可以进入交互模式，这样就和在浏览器开发者模式中的控制台直接使用 <code v-pre>JS</code> 没有差别了，并且打印出来的格式还蛮相似的，而使用 <code v-pre>.exit</code> 或者使用两次 <code v-pre>[ctrl+c]</code> 快捷键即可退出交互模式。</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 进入和退出 node 的交互模式</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> node</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Welcome</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Node.js</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> v16.20.2.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Type</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">.help</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> for</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> more</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> information.</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> console.log(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">"Hello World"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Hello</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> World</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">undefined</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> .exit</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">[</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ljp@VM-8-9-centos cpu: 3.2% mem: 52.05% - test</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">$</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>而且不仅仅是 <code v-pre>原生 JS</code> 代码，<code v-pre>Node.js</code> 应用的开发还比较特殊，在实现一个 <code v-pre>Node.js</code> 的 <code v-pre>HTTP</code> 服务器过程中，往往在一份 <code v-pre>.js</code> 代码中会包含以下步骤：</p>
<ul>
<li>使用 <code v-pre>require</code> 指令加载模块</li>
<li>创建服务器接受请求和返回响应</li>
</ul>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vim</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> cat</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">//</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 下面是一份简单的</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> HTTP</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 应用服务器代码</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">const</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> http</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> require</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">"http"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> //</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 这里引入了</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> http</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 模块,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 其实也可以放路径,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 不过使用</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Node.js</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 自带模块名字就会自动进行模块查找</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">const</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> server</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> http.createServer</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">function (</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">request,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> response</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> {</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> //</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 利用引入的模块实例变量来创建服务器应用</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    console.log(</span><span style="--shiki-light:#999999;--shiki-dark:#666666">`</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Received</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> ${</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">request.method</span><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> request for </span><span style="--shiki-light:#999999;--shiki-dark:#666666">${</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">request.url</span><span style="--shiki-light:#999999;--shiki-dark:#666666">}`</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">); // 查看对端的请求方法和路径, 这里使用反引号做插值打印</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    response.writeHead(200,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> {</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Content-Type</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">text/plain</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">}</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> //</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 设置响应的</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> HTTP</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 头部,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 包含状态值,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 状态说明,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 正文类型</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    response.end(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">'Hello World\n'</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> //</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 发送响应数据</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Hello World</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">}); // 但是这种设置方法只是配置了一个比较简单的 HTTP 服务器, 暂时没有设置对应的 HTTP 方法</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">server.listen(8080,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">0.0.0.0</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> () => { // 监听 8080 端口, 第二个 ip 参数如果不传, 默认使用 127.0.0.1</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    console.log(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">'Server running at http://0.0.0.0:8080/'</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> //</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 终端打印日志信息</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">});</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> node</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Server</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> running</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> at</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> http://0.0.0.0:8080/</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Received</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> GET</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> request</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> for</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Received</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> POST</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> request</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> for</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>对端我使用的是 <code v-pre>postman</code> 来充当客户端。</p>
<figure><img src="@source/1.编程语言/6.JavaScript/assets/image-20240801150305706.png" alt="image-20240801150305706" tabindex="0" loading="lazy"><figcaption>image-20240801150305706</figcaption></figure>
<figure><img src="@source/1.编程语言/6.JavaScript/assets/image-20240801150317471.png" alt="image-20240801150317471" tabindex="0" loading="lazy"><figcaption>image-20240801150317471</figcaption></figure>
<p>不过这种创建方式只是简单的 <code v-pre>HTTP</code> 服务器，还没有详细设置 <code v-pre>HTTP</code> 的方法，因此更加规范点可以写出如下的 <code v-pre>HTTP</code> 应用服务器，我直接把代码给出来，您可以自己在本地进行尝试，注意 <code v-pre>ip</code> 和 <code v-pre>port</code> 的修改。</p>
<div class="language-js line-numbers-mode" data-highlighter="shiki" data-ext="js" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-js"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">// 创建一份带有路由处理的 HTTP 服务器代码</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> express</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> require</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">express</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // 引入 express 模块, 这是比较流行的 JS Web 框架</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> app</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> express</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // 使用模块初始化一个 express 应用实例</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">get</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">/</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">req</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> res</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // 定义路由</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">    res</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">status</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">200</span><span style="--shiki-light:#999999;--shiki-dark:#666666">).</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">send</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Hello World</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">});</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> PORT</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 8080</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> HOST</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">0.0.0.0</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">app</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">listen</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">PORT</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> HOST</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> ()</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">    console</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">log</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">`</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Server running at http://</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">${</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">HOST</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">}</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">:</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">${</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">PORT</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">}</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">/</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">`</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">});</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_3-1-2-调试-js-代码" tabindex="-1"><a class="header-anchor" href="#_3-1-2-调试-js-代码"><span>3.1.2.调试 JS 代码</span></a></h4>
<p>不过，如果您不是把 <code v-pre>Node.js</code> 作为服务端开发使用，也完全可以把 <code v-pre>Node.js</code> 的 <code v-pre>node</code> 当做 <code v-pre>JS</code> 的开发工具，并且使用 <code v-pre>npm</code> 包管理器下载一下模块再进行编程（这点我们后面提及）。</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 使用 node inspect 对 JS 代码进行调试</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vim</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> cat</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> example</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    let</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    debugger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> //</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 这里使用</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> debugger</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 打了一个断点,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 调试器会在这里暂停</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    let</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> b</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    console.log(a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> +</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> b</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">example</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> node</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> inspect</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Debugger listening on ws://127.0.0.1:9229/21db8145-f19d-4200-bf92-9fe3ad4ccb2d</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> For help, see: https://nodejs.org/en/docs/inspector</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">connecting</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 127.0.0.1:9229</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ...</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ok</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Debugger attached.</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Break</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> on</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> start</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> in</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js:7</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">5</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   console.log</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> +</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> b</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">6</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> }</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 7 </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">example</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">8</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">9</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">debug</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">> </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">n</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">break</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> in</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test.js:3</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">1</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> function</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> example</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> {</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">2</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   let</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> 3</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   debugger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> //</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 调试器会在这里暂停</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">4</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   let</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> b</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">5</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   console.log</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> +</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> b</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">debug</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">> </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">c</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 3</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Waiting </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">for</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> the debugger to disconnect...</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">debug</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">> </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">.exit</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>相关的调试命令可以简单看一下：</p>
<ul>
<li><code v-pre>n</code> 继续执行到下一个断点</li>
<li><code v-pre>c</code> 继续执行直到程序结束</li>
<li><code v-pre>s</code> 单步进入</li>
<li><code v-pre>o</code> 单步跳过</li>
<li><code v-pre>repl</code> 进入交互模式</li>
</ul>
<h3 id="_3-2-使用-npm-工具" tabindex="-1"><a class="header-anchor" href="#_3-2-使用-npm-工具"><span>3.2.使用 npm 工具</span></a></h3>
<h4 id="_3-2-1-软件包管理" tabindex="-1"><a class="header-anchor" href="#_3-2-1-软件包管理"><span>3.2.1.软件包管理</span></a></h4>
<p>和许多包管理工具的行为类似，使用 <code v-pre>npm install &lt;Module Name@version&gt;</code> 即可快速进行第三方模块的安装，值得注意的是 <code v-pre>npm</code> 可以使用 <code v-pre>npm install npm -g</code> 自己升级自己，期间可能需要一点管理员权限。</p>
<p><code v-pre>-g</code> 选项可以指定为全局安装，这两种安装有所区别，并且非常有用，是避免冲突的有效解决方案。</p>
<ul>
<li>局部安装：不带 <code v-pre>-g</code> 的局部安装将安装包放在运行 <code v-pre>npm</code> 命令时所在的目录下（也就是 <code v-pre>./module_name</code>），如果需要在代码中使用必须通过 <code v-pre>require()</code> 来引入本地安装的包</li>
<li>全局安装：带上 <code v-pre>-g</code> 的全局安装将安装包放在 <code v-pre>/usr/local</code> 下或者 <code v-pre>node</code> 的安装目录，则可以直接在命令行里使用对应的应用，如果需要在代码中使用必须通过 <code v-pre>require()</code> 来引入本地安装的包</li>
</ul>
<p>因此有些情况下如果需要全局安装，很可能是为了通过 <code v-pre>npm</code> 下载一些第三方的命令行工具，而不单纯是为了编码工作。</p>
<p>也可以查看已经安装过的局部模块 <code v-pre>npm list</code> 同样可以加上 <code v-pre>-g</code> 选项查看全局下载的模块。</p>
<p>使用 <code v-pre>npm uninstall</code> 则可以卸载模块，同样也有加 <code v-pre>-g</code> 和不加 <code v-pre>-g</code> 的局部和全局区别。</p>
<blockquote>
<p>补充：这里还可以一个使用 <code v-pre>npm</code> 一个比较恶心的点，那就国外源的问题。使用 <code v-pre>npm</code> 下载模块时，有时会遇到网络连接的问题，至于解决方案，我这里只提供一种换源方案，还不行的话只能各显神通了。</p>
<ol>
<li>首先确保您的网络连接稳定，并且关闭任何防火墙或安全软件</li>
<li><code v-pre>npm cache clean --force</code> 清理 <code v-pre>npm</code> 缓存，有时清理 <code v-pre>npm</code> 缓存可以解决问题</li>
<li><code v-pre>npm install -g npm@latest</code> 尝试更新 <code v-pre>npm</code> 可能也会解决一些连接问题</li>
<li><code v-pre>npm config set registry https://registry.npmmirror.com</code> 尝试使用不同的 npm 注册表镜像，例如淘宝的 <code v-pre>npm</code> 镜像</li>
</ol>
<p>或者干脆使用淘宝镜像的 <code v-pre>cnpm</code> 替代 <code v-pre>npm</code> 的使用，执行 <code v-pre>sudo npm install -g cnpm --registry=https://registry.npmmirror.com</code> 就可以使用 <code v-pre>cnpm</code> 来替代 <code v-pre>npm</code> 的日常使用。</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 cnpm 来替代 npm 的使用</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -g</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> cnpm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --registry=https://registry.npmmirror.com</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">added</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> package</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> in</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 38s</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">59</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> packages</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> are</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> looking</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> for</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> funding</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  run</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> `</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> fund</span><span style="--shiki-light:#999999;--shiki-dark:#666666">`</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> for</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> details</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> cnpm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --version</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">cnpm@9.4.0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (C:</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\U</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">sers</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\L</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">imou_p350ml9</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\A</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ppData</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\R</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">oaming</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">pm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ode_modules</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\c</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">npm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\l</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ib</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\p</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">arse_argv.js)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm@9.9.2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (C:</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\U</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">sers</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\L</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">imou_p350ml9</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\A</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ppData</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\R</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">oaming</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">pm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ode_modules</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\c</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">npm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ode_modules</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">pm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\i</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ndex.js)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">node@20.10.0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (D:</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\A</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ppData</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\N</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ode.js</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ode.exe)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npminstall@7.12.0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (C:</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\U</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">sers</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\L</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">imou_p350ml9</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\A</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ppData</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\R</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">oaming</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">pm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ode_modules</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\c</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">npm</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ode_modules</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">pminstall</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\l</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ib</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\i</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ndex.js)</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">prefix</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">C:</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\U</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">sers</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\L</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">imou_p350ml9</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\A</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">ppData</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\R</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">oaming</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\n</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">pm</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">win32</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> x64</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 10.0.26120</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">registry</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">https://registry.npmmirror.com</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></blockquote>
<h4 id="_3-2-2-软件包配置" tabindex="-1"><a class="header-anchor" href="#_3-2-2-软件包配置"><span>3.2.2.软件包配置</span></a></h4>
<p>还有一种更加方便的下载方案，通常适用于大型项目部署的情况，就是使用 <code v-pre>package.json</code> 配置文件，然后使用。</p>
<p>您可以选择手动创建 <code v-pre>package.json</code> 文件，也可以使用 <code v-pre>npm init</code> 命令自动生成，一般我们推荐使用后者，只需要按照提示填写信息，<code v-pre>npm</code> 就会生成一个基础的 <code v-pre>package.json</code> 文件。如果希望使用默认配置，可以使用 <code v-pre>npm init -y</code></p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-shell"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 配置 package.json 的过程</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">$</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">       </span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">This</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> utility</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> will</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> walk</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> you</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> through</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> creating</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> package.json</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> file.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">It</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> only</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> covers</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> most</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> common</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> items,</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> and</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> tries</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> guess</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sensible</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> defaults.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">See</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> `</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> help init</span><span style="--shiki-light:#999999;--shiki-dark:#666666">`</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> for</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> definitive documentation on these fields</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">and</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> exactly</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> what</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> they</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> do.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Use</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> `</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">&#x3C;</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">pkg</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#999999;--shiki-dark:#666666">`</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> afterwards</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> install</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> package</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> and</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">save</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> it</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> as</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> dependency</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> in</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> package.json</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> file.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Press</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ^C</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> at</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> any</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> time</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> quit.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">package</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> name:</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (vuetest) my_package</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">version:</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (1.0.0) 1.2.1</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">description:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> a</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> self-made</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> software</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> package.</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">entry</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> point:</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (index.js) index.js</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">test</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> command:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> test</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">git</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> repository:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> https://github.com/limou3434/my_package.git</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">keywords:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> limou_package</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">author:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> limou3434</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">license:</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (ISC)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">About</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> write</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> D:</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\O</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">ther</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\v</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">uetest</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">\p</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">ackage.json:</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "name"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">my_package</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "version"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">1.2.1</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "description"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">a self-made software package.</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "main"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">index.js</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "scripts"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> {</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    "test"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">test</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  }</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "repository"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> {</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    "type"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">git</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    "url"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">git+https://github.com/limou3434/my_package.git</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">  },</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "keywords"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> [</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    "limou_package"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">  ],</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "author"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">limou3434</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "license"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">ISC</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">,</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "bugs"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> {</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    "url"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">https://github.com/limou3434/my_package/issues</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">  },</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  "homepage"</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">https://github.com/limou3434/my_package#readme</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">}</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Is</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> this</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> OK?</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (yes) yes</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>编写完毕后，使用 <code v-pre>npm install</code> 即可自动根据 <code v-pre>package.json</code> 文件进行安装（同样可以加上 <code v-pre>-g</code> 选项），使用 <code v-pre>npm start</code> 运行 <code v-pre>&quot;scripts&quot;</code> 中定义的脚本，也可以直接使用 <code v-pre>npm run 脚本名称</code> 来直接运行特定的脚本。使用 <code v-pre>npm publish</code> 可以对包进行发布。</p>
<p>可以看到 <code v-pre>package.json</code> 文件在 <code v-pre>Node.js</code> 项目中既可以用来描述项目的元数据（如项目名称、版本、描述等），也可以用作依赖管理的配置文件。</p>
<h2 id="_4-回调异步" tabindex="-1"><a class="header-anchor" href="#_4-回调异步"><span>4.回调异步</span></a></h2>
<p><code v-pre>Node.js</code> 异步编程的直接体现就是使用回调函数，<code v-pre>Node.js</code> 的异步编程依托于回调来实现，但不能说使用了回调后程序就异步化了。回调函数在完成任务后就会被调用，一个 <code v-pre>Node.js</code> 程序内部会使用大量的回调函数，<code v-pre>Node.js</code> 的所有 <code v-pre>API</code> 几乎都支持回调函数。</p>
<h2 id="_5-事件循环" tabindex="-1"><a class="header-anchor" href="#_5-事件循环"><span>5.事件循环</span></a></h2>
<h2 id="_6-事件触发器" tabindex="-1"><a class="header-anchor" href="#_6-事件触发器"><span>6.事件触发器</span></a></h2>
<h2 id="_7-缓冲区" tabindex="-1"><a class="header-anchor" href="#_7-缓冲区"><span>7.缓冲区</span></a></h2>
<h2 id="_8-流操作" tabindex="-1"><a class="header-anchor" href="#_8-流操作"><span>8.流操作</span></a></h2>
<h2 id="_9-模块系统" tabindex="-1"><a class="header-anchor" href="#_9-模块系统"><span>9.模块系统</span></a></h2>
<h1 id="" tabindex="-1"><a class="header-anchor" href="#"><span></span></a></h1>
<hr>
<blockquote>
<p>结语：...</p>
</blockquote>
</div></template>


