<template><div><p>内连接实际上就是利用 <code v-pre>WHERE</code> 子句（连接条件）对两张表形成的笛卡尔积（内连接）进行筛选，我们之前学习的查询基本都是内连接，也是在实际生产中被使用得最多的连接查询。</p>
<p>另外内连接还可以使用下面的语法形式来达成内连接：</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 内连接的语法形式</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">SELECT</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 字段 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">FROM</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 表1 [as] </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">INNER JOIN</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 表2 [as] </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">ON</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 连接条件 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">AND</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 其他条件;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>上述的语法形式比我们之前的笛卡尔积更加准确，语义更加明显，但结果一样。</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 尝试使用笛卡尔积的两种做法</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mysql</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> select</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> emp</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">ename</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">, </span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">dept</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">dname</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> emp, dept </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">where</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> emp</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">deptno</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">dept</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">deptno</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">--------+------------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| ename  | dname      |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">--------+------------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| clark  | accounting |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| king   | accounting |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| miller | accounting |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| smith  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| jones  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| scott  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| adams  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| ford   | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| allen  | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| ward   | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| martin | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| blake  | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| turner | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| james  | sales      |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">--------+------------+</span></span>
<span class="line"><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">14</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> rows</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> in</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> set</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">00</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> sec)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mysql</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> select</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> emp</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">ename</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">, </span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">dept</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">dname</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> emp </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">inner join</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> dept </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">where</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> emp</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">deptno</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">dept</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">deptno</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">--------+------------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| ename  | dname      |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">--------+------------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| clark  | accounting |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| king   | accounting |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| miller | accounting |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| smith  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| jones  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| scott  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| adams  | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| ford   | research   |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| allen  | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| ward   | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| martin | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| blake  | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| turner | sales      |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| james  | sales      |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">--------+------------+</span></span>
<span class="line"><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">14</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> rows</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> in</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> set</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">00</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> sec)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="_2-外连接" tabindex="-1"><a class="header-anchor" href="#_2-外连接"><span>2.外连接</span></a></h1>
<p>外连接本身又分为：<strong>左连接（左侧的表完全显示）</strong> 和 <strong>右连接（右侧的表完全显示）</strong>。</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 左连接和右连接的语法形式</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">SELECT</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 字段 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">FROM</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 表1 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">LEFT JOIN</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 表2 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">ON</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 连接条件;</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">SELECT</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 字段 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">FROM</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 表1 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">RIGHT JOIN</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 表2 </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">ON</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 连接条件;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们来实际操作一下就知道了：</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 左连接、右连接的使用</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mysql</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> select</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> stu;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| id   | </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">name</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | jack |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | tom  |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">3</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | kity |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">4</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | nono |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+</span></span>
<span class="line"><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">4</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> rows</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> in</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> set</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">00</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> sec)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mysql</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> select</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> exam;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+-------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| id   | grade |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+-------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">56</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">76</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|   </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">11</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |     </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">8</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+-------+</span></span>
<span class="line"><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">3</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> rows</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> in</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> set</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">00</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> sec)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)左连接：查询学生对应的成绩，但是如果有没找到的成绩，也必须把所有学生名字显示出来</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mysql</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> select</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> stu </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">left join</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> exam </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">on</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> stu</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">id</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">exam</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">id</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+------+-------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| id   | </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">name</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | id   | grade |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+------+-------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | jack |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">56</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | tom  |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">76</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">3</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | kity | </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">NULL</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |  </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">NULL</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">4</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | nono | </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">NULL</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |  </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">NULL</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+------+-------+</span></span>
<span class="line"><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">4</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> rows</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> in</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> set</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">00</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> sec)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)右连接：显示学生对应的成绩，但是如果没有找到的学生，也必须把所有成绩显示出来</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mysql</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> select</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> stu </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">right join</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> exam </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">on</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> stu</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">id</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">exam</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">id</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">;</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+------+-------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| id   | </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">name</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | id   | grade |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+------+-------+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | jack |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">56</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | tom  |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |    </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">76</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">NULL</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> | </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">NULL</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |   </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">11</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |     </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">8</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">------+------+------+-------+</span></span>
<span class="line"><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">3</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> rows</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> in</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> set</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">00</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> sec)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>补充：实际上右连接可以使用左连接替代，只需要调换一下表的先后顺序即可。</p>
</blockquote>
<h1 id="_3-using" tabindex="-1"><a class="header-anchor" href="#_3-using"><span>3.using()</span></a></h1>
<p>假设你有两个表 <code v-pre>A</code> 和 <code v-pre>B</code>，它们都有一个同名的列，若想要根据这个列将它们连接起来，您可以使用 <code v-pre>using</code> 查询：</p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-sql"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">-- 使用 using</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">select</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> A </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">join</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> B </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">using</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">(column_name);</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"># 等价于select </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">*</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> A </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">join</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> B </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">where</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> A</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">column_name</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">B</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">column_name</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>有时这点很有用，会比较方便进行反射查询。</p>
</div></template>


